version: "3"

volumes:
  postgres_data:

services:
  notification_service:
    restart: always
    container_name: notification_service
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - postgres
      - pgadmin
    volumes:
      - .:/usr/src/app
  postgres:
    restart: always
    container_name: postgres_container
    image: postgres:latest
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'